### ISSUE TITLE
Incorrect index.js path

### ISSUE THREAD

**Issue by owcs-solx** [insidewhy/friendship-blaster#50] opened 2020-11-27 07:52 UTC
`https://raw.githubusercontent.com/insidewhy/friendship-blaster/master/bin/friendship-blaster` uses `/home/fblaster/dist/index.js` but Docker image is `/home/fblaster/lib/index.js`.

**Comment by insidewhy** [comment] 2020-11-28 07:43
@owcs-solx The docker image has been updated to use `dist` in the latest version, where do you see it using `lib`? Maybe in an older version of friendship-blaster?

**Comment by insidewhy** [comment] 2020-11-28 07:44
See https://github.com/insidewhy/friendship-blaster/blob/master/bin/friendship-blaster#L61

**Comment by insidewhy** [comment] 2020-11-28 07:50
Build the latest version locally check this:

```bash
% docker run -it --rm xlos/friendship-blaster:1.0.0-beta.6 /bin/sh  
/home/fblaster # ls
Dockerfile     dist           node_modules   package.json   src            tsconfig.json  yarn.lock
```

Everything seems to be at `dist` rather than `lib` now.

**Comment by owcs-solx** [comment] 2020-11-28 08:49
@insidewhy This was reported by Nikhil while seeing up a new environment. Likely due to an outdated Docker image in the registry.

**Comment by insidewhy** [comment] 2020-11-28 10:52
I'll try pulling the latest release from the registry, might need to make a new release.

**Comment by owcs-solx** [comment] 2020-11-30 01:25
Looks to be the case. Last commit is 10 Apr. Docker images created date is 16 Mar.

**Comment by insidewhy** [comment] 2020-11-30 02:58
@owcs-solx I see, the problem is that the build script pulls the fblaster start script from git rather than using the version attached with the release it is using. For now I'll just push a new release once I've merged all the dependency upgrade PRs.

**Comment by insidewhy** [comment] 2020-11-30 07:47
@owcs-solx Pushed release `1.0.0-beta.7` to the docker registry, so now the script in git master reflects the path in the latest image version. It might be a better idea to have the server scripting pull the image using the git tag so that this kind of problem won't be encountered by that project in the future.

**Closed by insidewhy** 2020-11-30 07:47 UTC
